laser_scan_matcher:
  ros__parameters:
    publish_odom: "odom_cam"
    publish_tf: true
    base_frame: "base_link"
    odom_frame: "odom"
    map_frame: "map"
    laser_frame: "camera_link"
    sigma: 0.015 #Noise associated with depth camera for realsense D435
